weather_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: admin
      password: password
      dbname: weather_db
      schema: analytics
      threads: 4
